--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Crasher508/AdvancedReport
build-by-default: true
branches:
- master
projects:
  AdvancedReport:
    path: ""
    icon: "icon.png"
    libs:
    - src: jojoe77777/FormAPI/libFormAPI
      version: ^2.1.0
    - src: CortexPE/DiscordWebhookAPI/DiscordWebhookAPI
      version: ^1.0.1
...
