---
name: AdvancedReport
main: Crasher508\AdvancedReport\Main
version: 1.0.0
api: [3.0.0, 4.0.0]
authors:
- Crasher508
description: Addon for MyPlot
load: STARTUP
permissions:
  report.command:
    default: op
    children:
      report.command.add:
        default: true
      report.command.read:
        default: op
      report.command.delete:
        default: op
...
